### PR TITLE
same func

### PR DESCRIPTION
**Pull request by aizerin**
I have a two problem with this function.

1. name - I cannot use `equals` since it is already taken. And the meaning of `same` is a little bit different from `equals`. And I don't want to name it like `lensEquals` since it would be same as `propEq`. So the same is the best idea what I had.

2. my brain capacity is not enough to write it point-free. If anyone has idea I would be grateful.

### CODE REVIEW

**Comment by tommmyy** [comment]
Hi, I think `lensViewEq` is appropriate name... 

And for the point free version:

```
// Original version
const lensViewEq = curryN(3, (lens, eq, obj) => equals(view(lens, obj), eq));

// you can rewrite as:
const lensViewEq = (lens, eq, obj) => o(equals(eq), view(lens))(obj);

// then instead of "o" can be used "pipe"
const lensViewEq = (lens, eq, obj) => pipe(view(lens), equals(eq))(obj);

// then you can use useWith
const lensViewEq = useWith(pipe, [view, equals, identity])
```

**Comment by tommmyy** [comment]
And what about function `lensViewWith`

```
lensViewWith(lensIndex(0), pathEq(['foo'], 'boo'), [{ foo: 'boo' }]) // true

// implementation:

const lensViewWith = useWith(pipe, [view, identity, identity])
```

**Comment by jbradle** [comment]
Isn't that last identity useless?

**Comment by jbradle** [comment]
Also it does not work :-D

**Comment by jbradle** [comment]
My solution:
`const lensViewEq = useWith(flip(o), [view, equals])`
https://goo.gl/TQwtf1

**Comment by jbradle** [comment]
And why just not name it viewEq?

**Comment by aizerin** [comment]
done. I used George's solution since he has right with the pipe.

**Pull request merged**
