### PR TITLE
Reduce source

### PR DESCRIPTION
**Pull request by goldhand**
reduceSource allows reducing while referencing the source accumulator and array

### CODE REVIEW

**Comment by jbradle** [comment]
1. JSDoc has different order
2. Example can not be compiled
3. Not poit-free
4. Invasive contributor suggestion
5. Not signed commits

**Comment by tommmyy** [comment]
@goldhand any plan to check the review from @jbradle

**Comment by goldhand** [comment]
I was a bit alienated by the **"invasive contributor suggestion"** comment by @jbradle and decided to focus on other projects. I wasn't planning on updating this.

**Comment by tommmyy** [comment]
@goldhand I am really sorry for the 4. We did not specify any guidelines about "contributors" field. By me it is perfectly fine to be our contributor! I would like to see more!

**Comment by jbradle** [comment]
@goldhand Sorry if i offended you. I'm new in this, and also i had bad day.

**Comment by goldhand** [comment]
Thanks @jbradle, I'm sorry to hear that. Hopefully things are getting better.

I'll fix this pr this week (or weekend) @tommmyy

**Comment by goldhand** [comment]
Ok @tommmyy I think I've addressed all mentioned changes but I'm not sure if I was building the docs site correctly so I left those unchecked but I think they are ok, just want to confirm with you or @jbradle :

* [ ] JSDoc has different order 
* [ ] Example can not be compiled
* [x] Not poit-free
* [x] Not signed commits

**Comment by tommmyy** [comment]
@goldhand Thank you for your work!

**Pull request merged**
