### PR TITLE
CX benchmark

### PR DESCRIPTION
**Pull request by aizerin**
Many people ask about the performance of our `cx` against the original `classnames`. 

So I've created a test which reveals the cruel truth. We should try to work on the `cx` perfromance.

Current state is `Failed: cx is about 40 times slower`

### CODE REVIEW

**Comment by tommmyy** [comment]
In `cx`'s implementation there is  frequent usage of `map` filter. 
That can be improved.
And also few predicates can be saparated to own functions.

**Comment by aizerin** [comment]
Maybe also `transduce` can be handy.

**Comment by tommmyy** [comment]
I think we have a challenge. We need to make the alternative version of `cx` that:
1. run faster than `classnames` and
2. is written as pointfree

**Comment by aizerin** [comment]
I've been able to manage about 50% speed improvement so far.

**Comment by aizerin** [comment]
Our functionality exceeding the functionality of original classNames. We can cut it down for better performance results.

**Comment by tommmyy** [comment]
It makes sense... it may be be trivial then. Can you describe what
functionality we are going to cut down?

2018-04-19 10:03 GMT+02:00 aizerin <notifications@github.com>:

**Comment by jbradle** [comment]
Can you try to test it against deduple from classnames?

**Comment by aizerin** [comment]
I've dropped the `dedupe` functionality and I've been able to improve performance but we are still a lot of times slower than original impl. And I'm afraid that this is the maximum what we can get.

**Comment by tommmyy** [comment]
@aizerin Sorry for a late merge :)

**Pull request merged**
